### ISSUE TITLE
MacOS - Job fails on "Run leafo/gh-actions-lua@v6"

### ISSUE THREAD

**Issue by miguel-martinez-tfs** [leafo/gh-actions-lua#11]
Hi, I'm using a Mac as a self-hosted runner for Github actions. Echoing the $OSTYPE environment variable on my terminal prints "darwin17". However, I've noticed that the code only checks for "darwin". As a result, the job fails by trying to use apt-get (which doesn't exist on the machine).

https://github.com/leafo/gh-actions-lua/blob/cadf21f7e58d3a3b1eb72cd70581d5810391484f/main.js#L96

**Comment by Tieske** [comment]
seems like this can be closed?

**Comment by leafo** [comment]
Yeah, fixed awhile ago. Thanks
