### ISSUE TITLE
Update node_modules/@actions/core

### ISSUE THREAD

**Issue by siffiejoe** [leafo/gh-actions-lua#13]
The `node_modules` directory still contains an old version of the `@actions/core` module. Since the `add-path` and `set-env` commands in this module will be removed soon (see quotes below), the code as is will stop working. There is a similar issue with gh-actions-luarocks.

> The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by zarillion** [comment]
Indeed, this has happened. The build workflow in my repository now fails: https://github.com/zarillion/handynotes-plugins/runs/1410627335?check_suite_focus=true

The error is:

```
Error: Unable to process command '##[add-path]/home/runner/work/handynotes-plugins/handynotes-plugins/.lua/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

I use both this action and your `gh-actions-luarocks` action and they worked great. Would love a fix for this when you get a chance!

**Comment by alerque** [comment]
Ha! I just got burned by this one too, both through depending on this action and in some of my own. The deprecation timeline for this was pretty fast!

**Comment by edubart** [comment]
I got this error too today and my workflows are failing.

**Comment by leafo** [comment]
A tag for version 8.0.0 is now pushed that fixes the vendored libraries. Take note that I've switched to semantic versioning, `7` → `8.0.0`

**Comment by zarillion** [comment]
Works great now, thanks!
