### ISSUE TITLE
Specifying special build flags

### ISSUE THREAD

**Issue by daurnimator** [leafo/gh-actions-lua#16]
Sometimes I want to test with special compilation settings, e.g. with `LUA_CFLAGS="-DLUA_INT_TYPE=LUA_INT_INT"`.
How can I pass this through when compiling lua?

**Comment by leafo** [comment]
the `luaCompileFlags` input is passed direct to make, is that the right spot for those environment vars?

**Comment by daurnimator** [comment]
> the `luaCompileFlags` input is passed direct to make, is that the right spot for those environment vars?

doh. didn't see that option.

**Comment by leafo** [comment]
Looks like it's not in the docs, I've added it
