### ISSUE TITLE
Update Lua versions

### ISSUE THREAD

**Issue by alerque** [leafo/gh-actions-lua#20]
This past week I struggled with a couple of bugs that turned out to be Lua 5.4.3 issues (regressions from 5.4.2). They would have been caught earlier and more clearly if my CI had been running 5.4.3!

[Lua v5.4.4](https://github.com/lua/lua/releases/tag/v5.4.4) was just release.d This might be a good time to bump the matrix to the latest version ;-)

**Comment by leafo** [comment]
This has been fixed now in the latest version, `v9`
