### ISSUE TITLE
Lua 5.1 fails to install on ubuntu-latest

### ISSUE THREAD

**Issue by osyrisrblx** [leafo/gh-actions-lua#4]
Made a tiny repro here:
https://github.com/osyrisrblx/lua-test/runs/248671260#step:3:125

Seems to fail on `/usr/bin/ld: cannot find -lncurses` ?

Lua 5.2 installed just fine.

**Comment by osyrisrblx** [comment]
Ah shoot. This was my bad. Somehow I was using v2.

**Comment by leafo** [comment]
yeah, GitHub changed the default software on the ubuntu image recently and it breaks all old versions. I pushed a fix to master today. I'll put out a new versioned number soon
