### ISSUE TITLE
Lua 5.1 stopped working

### ISSUE THREAD

**Issue by alerque** [leafo/gh-actions-lua#5]
I have several projects with similar configs that test against a matrix of Lua versions. For some reason Lua 5.1 started failing, and not on my code .... on installing Lua.

Here is a public example: https://github.com/alerque/fluent-lua/pull/21

Is this an issue with this action?

**Comment by leafo** [comment]
Update to at least v5: https://github.com/leafo/gh-actions-lua/issues/4
